# App
app:
  name: Authentication Service
  description: Authenticate and verify users, devices and microservices.
  path: /usr/app/data

# JWT
jwt:
  secret-key: WvvhSWaLzE#3eTUU93RhLgh!c3io@YGqf7%9G5Sd*p3oNrjHVKF&E^Kx5N5zr9pUT#
  issuer:
  expiry-time-in-m: 120
  refresh-expiry-time-in-m: 120

# OAuth2
oauth2:
  client-id: auth-app-clientId
  client-secret: auth-app-clientSecret
  authorized-grant-types: client_credentials
  expiry-time-in-h: 6
  refresh-expiry-time-in-h: 6

# Actuator
management:
  endpoint:
    health:
      show-details: always
      probes:
        enabled: true

# Info
info:
  app:
    name: ${app.name}
    description: ${app.description}

# Logging
logging:
  level:
    root: info
    org.springframework.data: info
    com.mirgor.smarthome: info

# Logback
logback:
  destination:
    hostname: logstash
    port: 5044

# Server
server:
  port: 9100
  error:
    include-message: always
  servlet:
    context-path: /auth

spring:

  application:
    name: authentication

  # Distributed tracing
  zipkin:
    base-url: http://zipkin:9411/
  sleuth:
    sampler:
      probability: 1

  # Kubernetes
  cloud:
    kubernetes:
      enabled: true
      discovery:
        enabled: true

  # Mysql
  datasource:
    url: jdbc:mariadb://localhost:3306/authentication
    username: micro-jcon
    password: w4miTXcHXCXL45pbUnTBeVg
    driver-class-name: org.mariadb.jdbc.Driver
    initialization-mode: never
    #initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
