# App
app:
  name: Authentication Service
  path: /usr/app/data

# JWT
jwt:
  secret-key: WvvhSWaLzE#3eTUU93RhLgh!c3io@YGqf7%9G5Sd*p3oNrjHVKF&E^Kx5N5zr9pUT#
  issuer: Smarthome - Video server
  expiry-time-in-m: 0
  refresh-expiry-time-in-m: 60

# Actuator
management:
  endpoint:
    health:
      show-details: always

# Info
info:
  app:
    name: ${app.name}

# Logging
logging:
  level:
    root: info
    org.springframework.data: info
    com.mirgor.smarthome: info

# Logback
logback:
  destination:
    hostname: logstash
    port: 5044

# Load balancing
ribbon:
  http:
    client:
    #enabled=true:

# Web client:
web-client:
  conn-timeout: 3000
  read-timeout: 3000

# Clients
devices-service:
  url: localhost:8889
sdp:
  host: smarthomedesa.personal.com.ar
  uiapi:
    subscriber-url: https://${sdp.host}/UIAPI/Subscriber
  backofficeapi:
    subscriber-url: https://${sdp.host}/BackOfficeApi/REST/Subscribers?$expand=Parameters&$filter=PKID eq %s

# Feign
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

# Server
server:
  port: 9100
  error:
    include-message: always
  servlet:
    context-path: /auth

spring:

  application:
    name: authentication

    # Distributed tracing
    zipkin:
      base-url: http://zipkin:9411/

    sleuth:
      sampler:
        probability: 1

  # Mysql
  datasource:
    url: jdbc:mysql://localhost:3306/authentication
    username: authentication
    password: ohGhe2xoot6ohceengee
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: embedded
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
