# App
app:
  name: Authentication Service
  description: Authenticate and verify users, devices and microservices.
  path: /usr/app/data

# JWT
jwt:
  secret-key: WvvhSWaLzE#3eTUU93RhLgh!c3io@YGqf7%9G5Sd*p3oNrjHVKF&E^Kx5N5zr9pUT#
  issuer:
  expiry-time-in-m: 120
  refresh-expiry-time-in-m: 120

# Actuator
management:
  endpoint:
    health:
      show-details: always

# Info
info:
  app:
    name: ${app.name}
    description: ${app.description}

# Logging
logging:
  level:
    root: info
    org.springframework.data: info
    com.mirgor.smarthome: info

# Logback
logback:
  destination:
    hostname: logstash
    port: 5044

# Server
server:
  port: 9100
  error:
    include-message: always
  servlet:
    context-path: /auth

spring:

  application:
    name: authentication

    # Distributed tracing
    zipkin:
      base-url: http://zipkin:9411/
    sleuth:
      sampler:
        probability: 1

  # Mysql
  datasource:
    url: jdbc:mysql://localhost:3306/authentication
    username: authentication
    password: w4miTXcHXCXL45pbUnTBeVg
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: embedded
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
